routes:
  /:
    template: custom-home
    data: page.home
  /work/terra-design-system/:
    template: custom-casestudy-terra
    data: page.terra-design-system
  /work/seven-years-in-healthcare-ux/:
    template: custom-casestudy-cerner
    data: page.seven-years-in-healthcare-ux
  /work/domain-foundation/:
    template: custom-casestudy-domain-foundation
    data: page.domain-foundation
  /work/redwood-health-design/:
    template: custom-casestudy-redwood
    data: page.redwood-health-design
  /work/moonbird/:
    template: custom-casestudy-moonbird
    data: page.moonbird

collections:
  /writing/:
    permalink: /writing/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
